### ISSUE TITLE
Validate and cleanup annotations in SBML files

### ISSUE THREAD

**Issue by jonrkarr** [sys-bio/temp-biomodels#83]
Examples
- Publications with invalid PubMed ids
- Invalid identifiers.org namespaces

**Comment by luciansmith** [comment]
Did some digging on the final 7, and figured out six of them.  Four were obvious (in retrospect) errors where 'ncit' was used instead of 'ido' (the latter had several examples throughout the biomodels; some within the same model, even).  The last ncit one just needed a 'C' to point to the correct element, and I discovered an appropriate CHEBI term with the same number for the sixth.

The seventh was the BSU one, and I also couldn't find anything, so I just removed the reference.

So, with that, this issue can be closed!  https://github.com/sys-bio/temp-biomodels/commit/d542b1bcf12c29e239483677b90d2038134d684a
